### ISSUE TITLE
get strider github auth working

### ISSUE THREAD

**Issue by kfatehi** [kfatehi/saasbox-agent#6]
we just created a proper strider and mongo linked image because we had the below issue.

> why is github linking not working? we're shelled into the docker container here and trying to setup strider manually (newest code) to see if we may need to update the docker container.
> 
> looks like modules are fucked up -- lets build a new dockerfile that sets everything up properly.
> 
> we've left an instance on overnight. dont destroy it. get balance to show. ensure that when we destroy it, the balance transfers into the account.

**Comment by kfatehi** [comment]
aint working.

this is coming from strider still...

```
Express
500 failed to fetch user profile (status: 401 data: {"message":"Requires authentication","documentation_url":"https://developer.github.com/v3"})
at /opt/strider/node_modules/strider/node_modules/strider-github/node_modules/passport-github/lib/passport-github/strategy.js:90:28
at passBackControl (/opt/strider/node_modules/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:124:9)
at IncomingMessage. (/opt/strider/node_modules/strider/node_modules/strider-github/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:143:7)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:938:16
at process._tickCallback (node.js:419:13)
```

**Comment by kfatehi** [comment]
stupid fuckup. we fixed it in app
